AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template For Lambda Resource
Parameters: #No modificiar, sólo se agregan parámetros en caso de ser contenido sensible (passwords, access keys, etc)
  Environment: #No modificar
    Type: String
  Name: #No modificar
    Type: String
  Version:
    Type: String
Mappings:
  Configuration: #Sólo se modifican los valores si se ocupa un rol, vpc, subnets o security group diferentes al genérico
    dev:
      ReservedConcurrentExecutions: 1 #Sólo se modifica el valor si el área de Infraestructura lo permite
      LambdaSecurityGroupIds: #Sólo se modifica el valor si se requiere un security group diferente al genérico
        - sg-0376767cea75e42d8
      LambdaSubnetIds: #Sólo se modifica el valor si se requieren subnets diferentes a las genéricas
        - subnet-0f91adc19d1fc882b
        - subnet-093bbcc9af4bedffe
        - subnet-0db29cf0fa78e6ecb
      CodeDeployRole: service-role/DevOpsCodeDeploy #No se debe modificar
      CodeDeployType: CodeDeployDefault.LambdaAllAtOnce #No se debe modificar
      MemorySize: 1024 #Sólo se modifica el valor si el área de Infraestructura lo permite
      Timeout: 90 #Sólo se modifica el valor si el área de Infraestructura lo permite
    qa:
      ReservedConcurrentExecutions: 1 #Sólo se modifica el valor si el área de Infraestructura lo permite
      LambdaSecurityGroupIds: #Sólo se modifica el valor si se requiere un security group diferente al genérico
        - sg-0376767cea75e42d8
      LambdaSubnetIds: #Sólo se modifica el valor si se requieren subnets diferentes a las genéricas
        - subnet-0f91adc19d1fc882b
        - subnet-093bbcc9af4bedffe
        - subnet-0db29cf0fa78e6ecb
      CodeDeployRole: service-role/DevOpsCodeDeploy #No se debe modificar
      CodeDeployType: CodeDeployDefault.LambdaAllAtOnce #No se debe modificar
      MemorySize: 1024 #Sólo se modifica el valor si el área de Infraestructura lo permite
      Timeout: 90 #Sólo se modifica el valor si el área de Infraestructura lo permite
    prod:
      ReservedConcurrentExecutions: 1 #Sólo se modifica el valor si el área de Infraestructura lo permite
      LambdaSecurityGroupIds: #Sólo se modifica el valor si se requiere un security group diferente al genérico
        - sg-0376767cea75e42d8
      LambdaSubnetIds: #Sólo se modifica el valor si se requieren subnets diferentes a las genéricas
        - subnet-0f91adc19d1fc882b
        - subnet-093bbcc9af4bedffe
        - subnet-0db29cf0fa78e6ecb
      CodeDeployRole: service-role/DevOpsCodeDeploy #No se debe modificar
      CodeDeployType: CodeDeployDefault.LambdaAllAtOnce #No se debe modificar
      MemorySize: 1024 #Sólo se modifica el valor si el área de Infraestructura lo permite
      Timeout: 90 #Sólo se modifica el valor si el área de Infraestructura lo permite
Resources:
  LambdaRole: # No modificar nada
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: !Sub
        - "Role for lambda ${Name}"
        - { Name: !Ref Name }
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Path: /devops/
      Policies:
        - PolicyName: !Ref Name
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'lambda:InvokeFunction'
                Resource: !Sub
                  - 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:${Name}'
                  - { Name: !Ref Name }
      RoleName: !Ref Name
      Tags:
        - Key: "Type"
          Value: "devops"
  LambdaAlarm:
    Type: AWS::CloudWatch::Alarm
    DependsOn: LambdaFunction
    Properties:
      AlarmName: !Ref Name
      AlarmDescription: Alarma de pruebas
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Maximum
      Period: '60'
      EvaluationPeriods: '1'
      Threshold: '1'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Name
          Value:
            Ref: LambdaFunction
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref Name #No modificar
      CodeUri: dist #No modificar
      Handler: com.talentport.serverless.App::handleRequest #Modificable
      Runtime: java8 #Modificable
      MemorySize: !FindInMap [ Configuration, !Ref Environment, MemorySize ] #No modificar
      Timeout: !FindInMap [ Configuration, !Ref Environment, Timeout ] #No modificar
      Description: !Sub
        - "Release Version ${Version}"
        - { Version: !Ref Version } #Modificable
      ReservedConcurrentExecutions: !FindInMap [ Configuration, !Ref Environment, ReservedConcurrentExecutions ] #No modificar
      Policies: #No modificar
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - 'lambda:InvokeFunction'
              Resource: !Sub
                - 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:${Name}'
                - { Name: !Ref Name }
      Environment: #Sólo si lleva variables de entorno
        Variables:
          environment: !Ref Environment
          appName: !Ref Name
          version: !Ref Version
      AutoPublishAlias: live #No modificar
      Role: !Sub
        - "arn:aws:iam::${AWS::AccountId}:role/devops/${LambdaRole}" #No modificar
        - { LambdaRole: !Ref LambdaRole }
      DeploymentPreference: #No modificar
        Role: !Sub #No modificar
          - "arn:aws:iam::${AWS::AccountId}:role/${CodeDeployRole}" #No modificar
          - { CodeDeployRole: !FindInMap [ Configuration, !Ref Environment, CodeDeployRole ] }
        Type: !FindInMap [ Configuration, !Ref Environment, CodeDeployType ] #No modificar
      VpcConfig:
        SecurityGroupIds: !FindInMap [ Configuration, !Ref Environment, LambdaSecurityGroupIds ] #No modificar
        SubnetIds: !FindInMap [ Configuration, !Ref Environment, LambdaSubnetIds ] #No modificar